### ISSUE TITLE
Implement Big UInt Division (with remainder) for `modexp`

### ISSUE THREAD

**Issue by ilitteri** [lambdaclass/zksync_era_precompiles#129]
**Context:** `modexp.yul`

## Description: 

```solidity
/// @notice Performs the big unsigned integer square of big unsigned integers with an arbitrary amount of limbs.
/// @dev The quotient is stored from `quotientPtr` to `quotientPtr + (WORD_SIZE * nLimbs)`.
/// @dev The reminder is stored from `reminderPtr` to `reminderPtr + (WORD_SIZE * nLimbs)`.
bigUIntDivRem(dividendPtr, divisorPtr, nLimbs, quotientPtr, reminderPtr)
```

`dividendPtr`: The pointer to the MSB of the dividend.
`divisorPtr`: The pointer to the MSB of the divisor.
`nLimbs`: The number of limbs needed to represent the number to square.
`quotientPtr`: The pointer to where you want the quotient to be stored.
`remainderPtr`: The pointer to where you want the remainder to be stored.

## Subtasks:

- [x] [`sbb`](https://github.com/lambdaclass/lambdaworks/blob/main/math/src/unsigned_integer/element.rs#L795) #133 
- [x] [`ct_select`](https://github.com/lambdaclass/lambdaworks/blob/main/math/src/unsigned_integer/element.rs#L771) #134 
- [x] [`bitor`](https://github.com/lambdaclass/lambdaworks/blob/main/math/src/unsigned_integer/element.rs#L346) #132 
- [x] [`shl`](https://github.com/lambdaclass/lambdaworks/blob/main/math/src/unsigned_integer/element.rs#L512) #130 
- [x] [`shr`](https://github.com/lambdaclass/lambdaworks/blob/main/math/src/unsigned_integer/element.rs#L539) #131 

## Documentation

- [Lambdaworks `div_rem` implementation for unsigned integers](https://github.com/lambdaclass/lambdaworks/blob/8e0438adb11cdbcb404116a63f51970369102c62/math/src/unsigned_integer/element.rs#L822)
- [`crypto-bigint` implementation of div_rem](https://github.com/RustCrypto/crypto-bigint/blob/1d41918af8b585ea80978c1ae5c6e97e6a6a186d/src/uint/div.rs#L54)
- [`num-bigint` implementation of `div_rem`](https://docs.rs/num-bigint/latest/src/num_bigint/biguint/division.rs.html#119)

**Comment by jpcenteno** [comment]
Some tests i made

```yul
object "Playground" {
	code { }
	object "Playground_deployed" {
		code {
            function console_log(val) -> {
                let log_address := 0x000000000000000000636F6e736F6c652e6c6f67
                // A big memory address to store the function selector.
                let freeMemPointer := 0x400
                // store the function selector of log(uint256) in memory
                mstore(freeMemPointer, 0xf82c50f1) // mem[0] = 0xf8...
                // store the first argument of log(uint256) in the next memory slot
                mstore(add(freeMemPointer, 0x20), val)
                // call the console.log contract
                if iszero(staticcall(gas(),log_address,add(freeMemPointer, 28),add(freeMemPointer, 0x40),0x00,0x00)) {
                    revert(0,0)
                }
            }

            // PASTE FUNCTIONS FROM MODEXP HERE

            ////////////////////////////////////////////////////////////////
            //                      FALLBACK
            ////////////////////////////////////////////////////////////////

            function debug_log(v) {
                let debug_counter_ptr := 0x1000
                let debug_counter := mload(debug_counter_ptr)
                // "0xDeb006" means "debug".
                console_log(or(0xDeb0060000000000000000000000000000000000000000000000000000000000, debug_counter))
                console_log(v)
                mstore(debug_counter_ptr, add(debug_counter, 1)) // Increment debug counter
            }

            // +-----------------------------------------------------------------------------------+
            // | big_uint_shift_left_by_one_in_place tests                                         |
            // +-----------------------------------------------------------------------------------+

            mstore(0x00, 0xDEADBEEF) // For underflow checking purposes
            mstore(0x20, 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF) // a[0]
            mstore(0x40, 0x0) // a[1]
            mstore(0x60, 0x8000000000000000000000000000000000000000000000000000000000000000) // a[2]
            mstore(0x80, 0xF0000000000000000000000000000000000000000000000000000000DEADBEEF) // For overflow checking purposes
            big_uint_shift_left_by_one_in_place(0x20, 3)

            console_log(eq(mload(0x00), 0xDEADBEEF)) // Underflow check.
            console_log(eq(mload(0x20), 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFE)) // a[0]
            console_log(eq(mload(0x40), 0x0000000000000000000000000000000000000000000000000000000000000001)) // a[1]
            console_log(eq(mload(0x60), 0x0000000000000000000000000000000000000000000000000000000000000000)) // a[2]
            console_log(eq(mload(0x80), 0xF0000000000000000000000000000000000000000000000000000000DEADBEEF)) // Overflow check.


            // +-----------------------------------------------------------------------------------+
            // | big_uint_shift_right_by_one_in_place tests                                        |
            // +-----------------------------------------------------------------------------------+

            mstore(0x00, 0xDEADBEEF) // For underflow checking purposes
            mstore(0x20, 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFE) // a[0]
            mstore(0x40, 0x1) // a[1]
            mstore(0x60, 0x1) // a[2]
            mstore(0x80, 0xDEADBEEF) // For overflow checking purposes
            big_uint_shift_right_by_one_in_place(0x20, 3)

            console_log(eq(mload(0x00), 0xDEADBEEF)) // Underflow check.
            console_log(eq(mload(0x20), 0x7FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF)) // a[0]
            console_log(eq(mload(0x40), 0x0000000000000000000000000000000000000000000000000000000000000000)) // a[1]
            console_log(eq(mload(0x60), 0x8000000000000000000000000000000000000000000000000000000000000000)) // a[2]
            console_log(eq(mload(0x80), 0xDEADBEEF)) // Overflow check.

            // +-----------------------------------------------------------------------------------+
            // | big_uint_inplace_or_1 tests                                                       |
            // +-----------------------------------------------------------------------------------+

            let p := 0x0
            mstore(add(p, 0x00), 0x00) // v[0]
            mstore(add(p, 0x20), 0x00) // v[1]
            mstore(add(p, 0x40), 0xBADC0DE) // v[2] (For overflow checks).
            // Test case n=1
            big_uint_inplace_or_1(p, 1)
            console_log(eq(mload(add(p, 0x00)), 0x1))
            console_log(eq(mload(add(p, 0x20)), 0x0))
            console_log(eq(mload(add(p, 0x40)), 0xBADC0DE)) // Overflow check.
            // Test case n=2
            big_uint_inplace_or_1(p, 2)
            mstore(add(p, 0x00), 0x00) // Restore v[0]
            console_log(eq(mload(add(p, 0x00)), 0x0))
            console_log(eq(mload(add(p, 0x20)), 0x1))
            console_log(eq(mload(add(p, 0x40)), 0xBADC0DE)) // Overflow check.

            // +-----------------------------------------------------------------------------------+
            // | bigUIntDivRem tests                                                               |
            // +-----------------------------------------------------------------------------------+

            let nLimbs := 0x1

            let dividendPtr := 0x0
            mstore(add(dividendPtr, 0), 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF) // dividend[0]

            let divisorPtr := 0x20
            mstore(add(divisorPtr, 0), 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF) // divisor[0]

            let quotientPtr := 0x40
            mstore(add(quotientPtr, 0), 0x0) // quotient[0]

            let reminderPtr := 0x60
            mstore(add(reminderPtr, 0), 0x0) // reminder[0]

            bigUIntDivRem(dividendPtr, divisorPtr, nLimbs, quotientPtr, reminderPtr)

            // Comparing quotient against expected values:
            console_log(eq(mload(add(64, 0)), 0x1)) // quotient[0]

            // Comparing reminder against expected values:
            console_log(eq(mload(add(96, 0)), 0x0)) // reminder[0]


            // Test 02

            let nLimbs := 0x1

            let dividendPtr := 0x0
            mstore(add(dividendPtr, 0), 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF) // dividend[0]

            let divisorPtr := 0x20
            mstore(add(divisorPtr, 0), 0x8000000000000000000000000000000000000000000000000000000000000000) // divisor[0]

            let quotientPtr := 0x40
            mstore(add(quotientPtr, 0), 0x0) // quotient[0]

            let reminderPtr := 0x60
            mstore(add(reminderPtr, 0), 0x0) // reminder[0]

            bigUIntDivRem(dividendPtr, divisorPtr, nLimbs, quotientPtr, reminderPtr)

            // Comparing quotient against expected values:
            console_log(eq(mload(add(64, 0)), 0x1)) // quotient[0]

            // Comparing reminder against expected values:
            console_log(eq(mload(add(96, 0)), 0x7FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF)) // reminder[0]

            // Test 03
            // Perform a division where n_limbs == 1 and loops once.
            // Dividend = 0xFF..FF
            // Divisor = 0x4000.00 (remember 0x4 == 0b0100)
            // Expected bd = 1 // then, we shall loop once
            // Expected quotient = 0x3
            // Expected remainder = 0x3FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF

            let nLimbs := 0x1

            let dividendPtr := 0x0
            mstore(add(dividendPtr, 0), 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF) // dividend[0]

            let divisorPtr := 0x20
            mstore(add(divisorPtr, 0), 0x4000000000000000000000000000000000000000000000000000000000000000) // divisor[0]

            let quotientPtr := 0x40
            mstore(add(quotientPtr, 0), 0x0) // quotient[0]

            let reminderPtr := 0x60
            mstore(add(reminderPtr, 0), 0x0) // reminder[0]

            bigUIntDivRem(dividendPtr, divisorPtr, nLimbs, quotientPtr, reminderPtr)

            // Comparing quotient against expected values:
            console_log(eq(mload(add(quotientPtr, 0)), 0x3) // quotient[0]

            // Comparing reminder against expected values:
            console_log(eq(mload(add(reminderPtr, 0)), 0x3FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF)) // reminder[0]

		}
    }
}

```
